name: build-linux-amd64-zip

on:
  push:
    tags: [ 'v*' ]          # срабатывает при пуше тега v1.2.3
  workflow_dispatch:

jobs:
  build-zip:
    runs-on: ubuntu-latest

    steps:
    # ---------- checkout ----------
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
    - run: git submodule update --init --recursive

    # ---------- Rust toolchain ----------
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        target: x86_64-unknown-linux-musl

    # ---------- build ----------
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features --target=x86_64-unknown-linux-musl
        use-cross: true

    # ---------- pack ----------
    - run: |
        mkdir dist
        chmod a+x target/x86_64-unknown-linux-musl/release/*
        cp target/x86_64-unknown-linux-musl/release/{hbbs,hbbr,rustdesk-utils} dist/
        cd dist && zip -9 -r rustdesk-server-linux-amd64.zip *

    # ---------- upload as build artifact ----------
    - uses: actions/upload-artifact@v4
      with:
        name: rustdesk-server-linux-amd64.zip
        path: dist/rustdesk-server-linux-amd64.zip

    # ---------- attach to GitHub Release ----------
    - name: Create (draft) release and upload asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: dist/rustdesk-server-linux-amd64.zip
