name: build-linux-amd64

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

env:
  CARGO_TERM_COLOR: always
  LATEST_TAG: latest

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Init submodules (safety-net)
        run: git submodule update --init --recursive

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.82"
          override: true
          profile: minimal
          target: x86_64-unknown-linux-musl
          components: rustfmt

      - name: Build (release, musl)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target=x86_64-unknown-linux-musl
          use-cross: true

      - name: Make binaries executable
        run: chmod +x target/x86_64-unknown-linux-musl/release/*

      - name: Pack zip
        run: |
          sudo apt-get update -y
          sudo apt-get install -y zip
          zip -j rustdesk-server-linux-amd64.zip \
            target/x86_64-unknown-linux-musl/release/hbbs \
            target/x86_64-unknown-linux-musl/release/hbbr \
            target/x86_64-unknown-linux-musl/release/rustdesk-utils

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-server-linux-amd64
          path: rustdesk-server-linux-amd64.zip
          if-no-files-found: error

  github-release:
    needs: build-amd64
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: rustdesk-server-linux-amd64
          path: .

      - name: Publish draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: rustdesk-server-linux-amd64.zip
